In [141]:
import torch as t

# a = t.tensor(2.,requires_grad=True)
# b = a**2
# c = b.sum()
# # c.backward()
# t.autograd.grad(c,b)
x = t.randn(2, 3, 5, 5)
help(x.unfold)
# print(x)
# a = x.unfold(2, 3, 1)
# print(a.shape)

Help on built-in function unfold:

unfold(...) method of torch.Tensor instance
    unfold(dimension, size, step) -> Tensor
    
    Returns a view of the original tensor which contains all slices of size :attr:`size` from
    :attr:`self` tensor in the dimension :attr:`dimension`.
    
    Step between two slices is given by :attr:`step`.
    
    If `sizedim` is the size of dimension :attr:`dimension` for :attr:`self`, the size of
    dimension :attr:`dimension` in the returned tensor will be
    `(sizedim - size) / step + 1`.
    
    An additional dimension of size :attr:`size` is appended in the returned tensor.
    
    Args:
        dimension (int): dimension in which unfolding happens
        size (int): the size of each slice that is unfolded
        step (int): the step between each slice
    
    Example::
    
        >>> x = torch.arange(1., 8)
        >>> x
        tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.])
        >>> x.unfold(0, 2, 1)
        tensor([[ 1.,  2.],
       

$\mathrm{erf}(x) = \frac{2}{\sqrt{\pi}} \int_{0}^{x} e^{-t^2} dt$

$\mathrm{erfinv}(\mathrm{erf}(x)) = x$

$y_{i} = e^{x_{i}}$

$y_{i} = e^{x_{i}} - 1$

$\text{out}_{i} = \text{input}_{i} - \left\lfloor |\text{input}_{i}| \right\rfloor * \operatorname{sgn}(\text{input}_{i})$

$y_{i} = \log_{e} (x_{i})$

$y_{i} = \log_{10} (x_{i})$

$y_i = \log_{e} (x_i + 1)$

$\text{logsumexp}(x)_{i} = \log \sum_j \exp(x_{ij})$

In [95]:
class Relu(t.autograd.Function):
    @staticmethod
    def forward(ctx, input):
        output = t.clamp(input, min=0)
        ctx.save_for_backward(output)
        return output

    @staticmethod
    def backward(ctx, grad_output):
        output = ctx.saved_tensors[0]
        print(output)
        print(grad_output)
        return (output > 0).float() * grad_output


x = t.randn(2, 3, requires_grad=True)
y = Relu.apply(x)
loss = y.sum()
loss.backward()
x
x.grad


tensor([[0.3176, 0.0000, 0.0000],
        [0.0000, 1.5142, 0.4916]], grad_fn=<ReluBackward>)
tensor([[1., 1., 1.],
        [1., 1., 1.]])


tensor([[1., 0., 0.],
        [0., 1., 1.]])

In [131]:
m = t.arange(16).view(4, 4)
m.shape, m.size()

(torch.Size([4, 4]), torch.Size([4, 4]))